const projects=[
{id:1,title:'Land Cover Change Prediction — Bontang City',cat:'Spatial Modelling',tools:['GeoSOS-FLUS','Markov Chain','GIS'],img:'assets/projects/bontang.png',desc:'This project predicts land cover change in Bontang City over the next 20 years using the Markov Chain method in GeoSOS-FLUS. The analysis uses historical land-cover patterns to model future spatial changes and understand the potential direction of urban and industrial development. Results show an 8.28 km² increase in built-up areas and significant loss of forests and vegetation due to urbanization and industrial growth. The findings provide a spatial understanding of future land-cover transformation and highlight the importance of land-use management, green-area protection, and sustainable urban and industrial planning.',details:'This project predicts land cover change in Bontang City over the next 20 years using the Markov Chain method in GeoSOS-FLUS. The analysis combines historical land-cover patterns with spatial modelling to project future development scenarios. Results show an 8.28 km² increase in built-up areas and significant loss of forests and vegetation due to urbanization and industrial growth. The resulting spatial projections provide insights into future land-use transformation and support land-use management, green-area protection, and more sustainable urban and industrial planning.'},
{id:2,title:'Morphological Analysis — Bromo Tengger Semeru National Park',cat:'Terrain Analysis',tools:['DEM','Elevation','Slope','GIS'],img:'assets/projects/bromo.png.png',desc:'This study maps the morphology of Bromo Tengger Semeru National Park using DEM-derived elevation and slope data. Terrain characteristics were analyzed using Raster Calculator for raster-based calculations and raster reclassification to group elevation and slope values into meaningful terrain classes. Results show that over 75% of the area is dominated by steep and moderately steep terrain, shaped by volcanic activity around Mount Semeru and Bromo. These findings provide essential insights for understanding landscape morphology and support conservation planning, disaster risk mitigation, and sustainable land management.',details:'This study maps the morphology of Bromo Tengger Semeru National Park using DEM-derived elevation and slope data. The analysis derived terrain characteristics from DEM data and used Raster Calculator to support raster-based calculations, followed by raster reclassification to group elevation and slope values into meaningful terrain classes. Results show that over 75% of the area is dominated by steep and moderately steep terrain, shaped by volcanic activity around Mount Semeru and Bromo. The resulting terrain classification supports interpretation of landscape morphology and provides essential insights for conservation planning, disaster risk mitigation, and sustainable land management.'},
{id:3,title:'Economic Dynamics of Yogyakarta with Night-Time-Light Imagery',cat:'Remote Sensing',tools:['NTL','Dasymetric Mapping','GEE','ArcGIS'],img:'assets/projects/yogyakarta.png',desc:'This study estimates the GRDP of Yogyakarta Special Region using Night-Time Light (NTL) imagery, land cover, and population data with dasymetric mapping. The analysis integrates remotely sensed nighttime illumination with demographic and land-cover information to spatially estimate economic activity beyond conventional administrative statistics. Results show that Yogyakarta City has the highest economic activity compared to other districts, supported by its high urban intensity. The findings demonstrate that NTL is effective for spatial economic analysis and provides an additional evidence base for data-driven development planning and regional decision-making.',details:'This study estimates the GRDP of Yogyakarta Special Region using Night-Time Light (NTL) imagery, land cover, and population data with dasymetric mapping. The workflow integrates spatial indicators to distribute estimated economic activity more realistically across the study area rather than relying only on administrative boundaries. Results show that Yogyakarta City has the highest economic activity compared to other districts, supported by its high urban intensity. The findings demonstrate that NTL is effective for spatial economic analysis and can provide an additional evidence base for data-driven development planning and regional decision-making.'},
{id:4,title:'Solar Energy Potential Analysis — Surabaya',cat:'Renewable Energy',tools:['LiDAR','nDSM','ArcGIS','SolarGIS'],img:'assets/projects/solar-surabaya.png (1).jpg',fallback:'assets/projects/solar-surabaya.svg',desc:'This project analyzes the solar energy potential of Surabaya using LiDAR-derived nDSM processed with the ArcGIS Area Solar Radiation tool. The analysis maps annual rooftop solar potential and assesses the spatial variability of solar irradiance (kWh/m²/year) by considering building orientation, shading, land cover, and urban density. The workflow integrates rooftop characteristics and solar-radiation modelling to identify differences in potential across the urban area. It further estimates rooftop photovoltaic electricity generation potential of up to approximately 234 kWh/m²/year per panel based on solar radiation data, module efficiency, and performance ratio assumptions, providing a spatial basis for renewable-energy planning.',details:'This project analyzes the solar energy potential of Surabaya using LiDAR-derived nDSM processed with the ArcGIS Area Solar Radiation tool. The workflow integrates building footprints, land cover, terrain and rooftop characteristics to map annual solar irradiance and assess its spatial variability across the city, considering factors such as building orientation, shading, land cover, and urban density. The study also estimates rooftop photovoltaic electricity generation potential of up to approximately 234 kWh/m²/year per panel based on solar radiation data, module efficiency, and performance ratio assumptions.'},
{id:5,title:'Urban Expansion Map — Surabaya',cat:'WebGIS',tools:['WebGIS','ArcGIS','Interactive Map'],img:'assets/projects/urban-expansion.png',link:'https://www.arcgis.com/apps/instant/interactivelegend/index.html?appid=c2fde39bcc9946b5806501e0cbb77742&center=112.7028;-7.2932&level=10',desc:'This map shows the growth and distribution of population in Surabaya City from 1995 to 2025. The distribution of the population tends to point to the east and north, illustrating the spatial direction of population concentration and urban growth over time. The interactive map provides a visual basis for understanding changing population patterns and the direction of urban expansion.',details:'This map shows the growth and distribution of population in Surabaya City from 1995 to 2025. The distribution of the population tends to point to the east and north, providing a visual representation of population concentration and urban expansion over time. The interactive WebGIS supports interpretation of changing population distribution and can help stakeholders consider future infrastructure, urban development, and spatial planning needs.'},
{id:6,title:'Spatio-Temporal Deforestation Modeling — West Sumatra',cat:'Remote Sensing',tools:['Google Earth Engine','Landsat','NDFI'],img:'assets/projects/deforestation.png.png',fallback:'assets/projects/deforestation.svg',desc:'The Spatio-Temporal Deforestation Modeling Project in West Sumatra (Nov 2025–Dec 2025) involved analyzing multitemporal Landsat imagery from 2009 to 2024 using Google Earth Engine to identify patterns of forest loss, degradation, and regrowth. The workflow applied vegetation index–based thresholding and the Normalized Difference Fraction Index (NDFI) to detect deforestation dynamics, hotspots, and temporal change trajectories. The analysis produced spatial outputs such as deforestation maps, hotspot analyses, temporal comparisons, and comparative method evaluations, providing evidence for environmental monitoring and spatial planning decision-making.',details:'The Spatio-Temporal Deforestation Modeling Project in West Sumatra (Nov 2025–Dec 2025) involved analyzing multitemporal Landsat imagery from 2009 to 2024 using Google Earth Engine to identify patterns of forest loss, degradation, and regrowth. The workflow applied vegetation index–based thresholding and the Normalized Difference Fraction Index (NDFI) to detect deforestation dynamics, hotspots, and temporal change trajectories. Spatial outputs included deforestation maps, hotspot analyses, temporal comparisons, and comparative evaluations of detection methods.'},
{id:7,title:'Potential Campus Transit Stop Locations — ITS, PENS & PPNS',cat:'Transportation & WebGIS',tools:['UNA','SNA','3D WebGIS','MapLibre'],img:'assets/projects/Project%207.png',link:'https://hazidien.github.io/Potensi-Lokasi-Halte-ITS/',desc:'This project develops a 3D WebGIS using Urban Network Analysis (UNA) and Service Network Analysis (SNA) to identify buildings with high potential for campus transit stops across ITS, PENS, and PPNS. The analysis evaluates network accessibility and service coverage to support integrated campus transportation planning.',details:'This project develops a 3D WebGIS using Urban Network Analysis (UNA) and Service Network Analysis (SNA) to identify buildings with high potential for campus transit stops across ITS, PENS, and PPNS. The analysis evaluates network accessibility and service coverage to identify potential locations that can improve connectivity between campus areas. Results are visualized interactively through a 3D MapLibre WebGIS to support integrated campus transportation planning.'},
{id:8,title:'Deforestation Monitoring WebGIS Using Landsat Time-Series and Google Earth Engine',cat:'WebGIS & Remote Sensing',tools:['Google Earth Engine','Landsat','WebGIS','Time Series'],img:'assets/projects/Project%208.png',link:'https://crispy-space-xylophone-pjj7g6575pxp29rg6-8000.app.github.dev/',desc:'This project develops an interactive WebGIS for monitoring forest cover and deforestation using multi-temporal Landsat imagery and Google Earth Engine (GEE). The system features cloud masking, temporal compositing, forest classification, AOI-based analysis, time-series visualization, and exportable results from 1990–2020.',details:'This project develops an interactive WebGIS for monitoring forest cover and deforestation using multi-temporal Landsat imagery and Google Earth Engine (GEE), featuring cloud masking, temporal compositing, forest classification, AOI-based analysis, time-series visualization, and exportable results from 1990–2020. The WebGIS was developed through prompt engineering and AI-assisted coding using GPT-based AI, with the workflow, requirements, and system design directed and refined by the developer. The demo is available through GitHub Codespaces and requires the backend service to be active; it is not continuously hosted.'},
{id:9,title:'Interactive Air Pollution WebGIS Using Sentinel-5P and Google Earth Engine',cat:'WebGIS & Remote Sensing',tools:['Sentinel-5P','Google Earth Engine','WebGIS','Time Series'],img:'assets/projects/Project%209.png',link:'https://obscure-space-lamp-g44x5pvxvrjwh955p-8000.app.github.dev/',desc:'This project develops an interactive WebGIS for analyzing atmospheric pollution using Sentinel-5P and Google Earth Engine. Users can select pollutants, define dates and AOI, and generate spatial concentration maps, statistics, and time-series visualizations.',details:'This project develops an interactive WebGIS for analyzing atmospheric pollution using Sentinel-5P and Google Earth Engine. Users can select pollutants, define dates and an Area of Interest (AOI), and generate spatial concentration maps, statistical summaries, and time-series visualizations. The WebGIS was developed through prompt engineering and AI-assisted coding using GPT-based AI, with the workflow, requirements, and system design directed and refined by the developer. The demo is available through GitHub Codespaces and requires an active backend service; it is not continuously hosted.'}
];
const grid=document.querySelector('#projectGrid');const modal=document.querySelector('#projectModal');const modalBody=document.querySelector('#modalBody');
function imageTag(p,modalMode=false){const fallback=p.fallback?` onerror="this.onerror=null;this.src='${p.fallback}'"`:'';return `<img class="project-img" src="${p.img}" alt="${p.title} project visualization"${fallback}${modalMode?' style="border-radius:16px;margin:15px 0 20px"':''}>`}
function render(list=projects){grid.innerHTML=list.map(p=>`<article class="project reveal" tabindex="0" role="button" aria-label="View ${p.title}" onclick="openProject(${p.id})" onkeydown="if(event.key==='Enter')openProject(${p.id})">${imageTag(p)}<div class="project-body"><div class="section-kicker">${p.cat}</div><h3>${p.title}</h3><div class="tags">${p.tools.map(t=>`<span class="tag">${t}</span>`).join('')}</div><p>${p.desc}</p><span class="more">${p.link?'Open project ↗':'Click to read more →'}</span></div></article>`).join('');observeReveals()}
function openProject(id){const p=projects.find(x=>x.id===id);const action=p.link?`<a class="btn primary" href="${p.link}" target="_blank" rel="noopener">Open Project ↗</a>`:'';modalBody.innerHTML=`<div class="section-kicker">${p.cat}</div><h2>${p.title}</h2><p class="modal-meta">${p.tools.join(' · ')}</p>${imageTag(p,true)}<p>${p.details}</p><div class="tags">${p.tools.map(t=>`<span class="tag">${t}</span>`).join('')}</div>${action}`;modal.classList.add('open');document.body.style.overflow='hidden'}
function closeProject(){modal.classList.remove('open');document.body.style.overflow=''}document.querySelector('#closeModal').onclick=closeProject;modal.addEventListener('click',e=>{if(e.target===modal)closeProject()});
const evidenceModal=document.querySelector('#evidenceModal');const evidenceBody=document.querySelector('#evidenceBody');
function openEvidence(title,src,type='image'){evidenceBody.innerHTML=`<div class="section-kicker">Work Evidence</div><h2>${title}</h2>${type==='image'?`<img src="${src}" alt="${title}">`:''}`;evidenceModal.classList.add('open');document.body.style.overflow='hidden'}
function closeEvidence(){evidenceModal.classList.remove('open');document.body.style.overflow=''}evidenceModal.addEventListener('click',e=>{if(e.target===evidenceModal)closeEvidence()});
const certificateModal=document.querySelector('#certificateModal');const certificateBody=document.querySelector('#certificateBody');
function closeCertificate(){certificateModal.classList.remove('open');document.body.style.overflow=''}certificateModal.addEventListener('click',e=>{if(e.target===certificateModal)closeCertificate()});
const certificateAssets={
  'LiDAR Data Classification & Contour Generation':{type:'pdf',src:'assets/sertif%20lidar.pdf'},
  'Land Cover Change Prediction using QGIS & GeoSOS-FLUS':{type:'image',src:'assets/landuse_sertifikat.jpg'},
  'Basic & Thematic Google Earth Engine':{type:'pdf',src:'assets/sertif%20gee.pdf'},
  'Geographic Information System Training':{type:'image',src:'assets/sertif_hecras2.jpg',title:'Flood Modeling of Land Use Change & Prediction'}
};
function openCertificate(title,provider){const asset=certificateAssets[title]||certificateAssets['Geographic Information System Training'];const displayTitle=asset.title||title;certificateBody.innerHTML=`<div class="section-kicker">Certificate</div><h2>${displayTitle}</h2><p class="modal-meta">${provider||''}</p>${asset.type==='pdf'?`<iframe class="certificate-frame" src="${asset.src}#toolbar=1&navpanes=0&scrollbar=1" title="${displayTitle} certificate"></iframe>`:`<img class="certificate-image" src="${asset.src}" alt="${displayTitle} certificate">`}`;certificateModal.classList.add('open');document.body.style.overflow='hidden'}
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeProject();closeEvidence();closeCertificate()}});
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');const c=b.dataset.filter;render(c==='all'?projects:projects.filter(p=>p.cat===c))}));const menu=document.querySelector('#menu');const nav=document.querySelector('#navLinks');menu.addEventListener('click',()=>nav.classList.toggle('open'));document.querySelectorAll('.nav-links a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));function observeReveals(){const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal:not(.visible)').forEach(x=>io.observe(x))}render();
const certificateStyle=document.createElement('style');certificateStyle.textContent=`
.project-body>p{display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:4;overflow:hidden;min-height:6.2em;margin-bottom:18px}
.project .more{display:inline-block;margin-top:auto;color:#5bd0ff;font-weight:700;letter-spacing:.01em}
.certificate-image{width:100%;height:auto;max-height:78vh;object-fit:contain;border-radius:16px;display:block;background:#06101c;margin-top:15px}
.social,.social:visited,.social:hover,.social:active{color:#fff;text-decoration:none}
.btn,.btn:visited,.btn:hover,.btn:active{color:#fff;text-decoration:none}
.btn.primary,.btn.primary:visited,.btn.primary:hover,.btn.primary:active{color:#07111f}
.nav-links a,.nav-links a:visited{color:#fff;text-decoration:none}
`;document.head.appendChild(certificateStyle);