const projects=[
{id:1,title:'Land Cover Change Prediction — Bontang City',cat:'Spatial Modelling',tools:['GeoSOS-FLUS','Markov Chain','GIS'],img:'assets/projects/bontang.svg',desc:'Predicted land-cover change in Bontang City over 20 years. The portfolio study reports an 8.28 km² increase in built-up area and loss of forest and vegetation associated with urbanization and industrial growth.',details:'The project used GeoSOS-FLUS with a CA-Markov approach to project future land cover. The analysis was translated into planning recommendations including vertical housing, green-area protection, and improved waste management.'},
{id:2,title:'Morphological Analysis — Bromo Tengger Semeru National Park',cat:'Terrain Analysis',tools:['DEM','Elevation','Slope','GIS'],img:'assets/projects/bromo.svg',desc:'Mapped the morphology of Bromo Tengger Semeru National Park using DEM-derived elevation and slope data.',details:'The study classified terrain using elevation and slope thresholds and found that more than 75% of the landscape was dominated by steep and moderately steep terrain. The results support conservation, disaster-risk mitigation, and sustainable land management.'},
{id:3,title:'Economic Dynamics of Yogyakarta with Night-Time-Light Imagery',cat:'Remote Sensing',tools:['NTL','Dasymetric Mapping','GEE','ArcGIS'],img:'assets/projects/yogyakarta.svg',desc:'Estimated GRDP spatially using night-time-light imagery, land cover, population data, and dasymetric mapping.',details:'The analysis mapped economic activity spatially and found Yogyakarta City to have the highest estimated economic activity among the districts studied. The project demonstrates how NTL can support spatial economic analysis.'},
{id:4,title:'Solar Energy Potential Analysis — Surabaya',cat:'Renewable Energy',tools:['LiDAR','nDSM','ArcGIS','SolarGIS'],img:'assets/projects/solar-surabaya.svg',desc:'Assessed rooftop solar potential using LiDAR-derived nDSM and ArcGIS Area Solar Radiation modelling.',details:'The work integrated building footprints, land use, LiDAR-derived rooftop data, and solar radiation across 31 districts in Surabaya. The CV reports validation against SolarGIS with RMSE 143.40 kWh/m²/year and 7.36% relative error. The portfolio reports PV generation potential up to approximately 234 kWh/m²/year per panel under stated assumptions.'},
{id:5,title:'Urban Expansion Map — Surabaya',cat:'WebGIS',tools:['WebGIS','ArcGIS','Interactive Map'],img:'assets/projects/urban-expansion.svg',desc:'Interactive map showing population growth and distribution in Surabaya from 1995 to 2025.',details:'The project visualizes temporal urban expansion and population distribution to support interpretation of spatial growth and future planning decisions.'},
{id:6,title:'Spatio-Temporal Deforestation Modeling — West Sumatra',cat:'Remote Sensing',tools:['Google Earth Engine','Landsat','NDFI'],img:'assets/projects/deforestation.svg',desc:'Analyzed multitemporal Landsat imagery from 2009–2024 to identify forest loss, degradation, regrowth, hotspots, and temporal trajectories.',details:'The workflow used Google Earth Engine, vegetation-index thresholding, and the Normalized Difference Fraction Index (NDFI). AI-assisted code was critically evaluated and refined for methodological logic, parameter choices, spatial bias, and uncertainty.'}
];
const grid=document.querySelector('#projectGrid');const modal=document.querySelector('#projectModal');const modalBody=document.querySelector('#modalBody');
function render(list=projects){grid.innerHTML=list.map(p=>`<article class="project reveal" tabindex="0" role="button" aria-label="View ${p.title}" onclick="openProject(${p.id})" onkeydown="if(event.key==='Enter')openProject(${p.id})"><img class="project-img" src="${p.img}" alt="${p.title} project visualization"><div class="project-body"><div class="section-kicker">${p.cat}</div><h3>${p.title}</h3><div class="tags">${p.tools.map(t=>`<span class="tag">${t}</span>`).join('')}</div><p>${p.desc}</p><span class="more">View project →</span></div></article>`).join('');observeReveals()}
function openProject(id){const p=projects.find(x=>x.id===id);modalBody.innerHTML=`<div class="section-kicker">${p.cat}</div><h2>${p.title}</h2><p class="modal-meta">${p.tools.join(' · ')}</p><img class="project-img" src="${p.img}" alt="${p.title}" style="border-radius:16px;margin:15px 0 20px"><p>${p.details}</p><div class="tags">${p.tools.map(t=>`<span class="tag">${t}</span>`).join('')}</div>`;modal.classList.add('open');document.body.style.overflow='hidden'}
function closeProject(){modal.classList.remove('open');document.body.style.overflow=''}document.querySelector('#closeModal').onclick=closeProject;modal.addEventListener('click',e=>{if(e.target===modal)closeProject()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeProject()});
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');const c=b.dataset.filter;render(c==='all'?projects:projects.filter(p=>p.cat===c))}));const menu=document.querySelector('#menu');const nav=document.querySelector('#navLinks');menu.addEventListener('click',()=>nav.classList.toggle('open'));document.querySelectorAll('.nav-links a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));function observeReveals(){const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal:not(.visible)').forEach(x=>io.observe(x))}render();
